-- 1. Create profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  college text,
  verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create confessions table
create table confessions (
  id bigint generated by default as identity primary key,
  content text not null,
  created_by uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create polls table
create table polls (
  id bigint generated by default as identity primary key,
  question text not null,
  options text[] not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
